= Content views and composite content views
:hp-tags: satellite6, content views, youtube

We have been talking about content views in the previous posts, but to be sure we are all on the same page: a content view is a versioned, filtered set of repositories that you can promote between lifecycle environments. We have been talking about 'normal' content views, or CV, up until now, but Satellite 6 also knows the concept of a _composite content view_, or CCV.

A composite content view allows you to bundle other content views, rather than individual repositories. The best approach to this is to start creating re-usable building blocks (component content views) to bundle in CCVs. You could, for example, create a building block for the base operating system, and combine that with different application content views into composite content views. 

You might want to do this if your application content views follow different lifecycle paths, or move slower (or faster) than your base operating system content view through the same lifecycle path.

Another use case would be if the application content view is maintained by a different department. By using composite content views in that case, the team of application administrators or developers can manage the application content view, and the Linux administrator team can manage the base operating system content view. Every once in a while - depending on requirements - the two component CVs are bundled together into a CCV, and then published and promoted.

You then use activation keys to register new systems to the CCV and use the provisions in that activation key to grant access to specific repositories in the CCV. (This will be the topic of a later video.)

I created this episode because people often ask what the difference is between CVs and CCVs, and if they should always use CCVs. I want to be clear about that last question. The answer to it is a distinct _no_. Do _not_ use CCVs just because you can. _Do_ use CCVs because you are trying to solve one of the use cases mentioned above, or one of the use cases mentioned in the https://access.redhat.com/articles/1585273[10 Steps to Build an SOE with Satellite 6] document. For those cases, CCVs are perfect :)

Hope you enjoy the video! Please subscribe and leave any comments here, or on YouTube, whichever you prefer!

Until next time!

video::BJjAWME1TlQ[youtube]