= Video: Updating your Satellite 6 system
:hp-tags: youtube, satellite6, updates

Recently, I was talking to a customer about Satellite updates. We have released quite a few over the last six months, and he and his co-workers were a little anxious about updating their Satellite each time, as it is a vital piece of their infrastructure.

As we discussed the fact that updating a Satellite is actually a really simple procedure, it occured to me that it would make sense to pause the video series about content views for a bit. Instead of a content view video, I'm going to dedicate one video to showing the simple steps of safely and correctly updating a Satellite server. 

This is a really short one - as I hope to have more - that walks you quickly through the steps of updating a Satellite 6 system:

1. identifying that there is an update outstanding
2. installing the updated packages
3. making sure any database migrations and mandatory configuration file changes are applied

The video below will take you through these steps and make sure you are prepared for your next Satellite 6 update! :)