= Red Hat Tech Day Demo Recordings (June 2017)
:published_at: 2017-06-14
:hp-tags: Red Hat, CDK, OpenShift, containers, development, Java, .Net, Python

So last Tuesday, I presented about Red Hat's container development kit during the Red Hat Tech Day in Utrecht (NL). 

Though most of the demos succeeded eventually, they all took way longer than expected due to some network issues. I'll be frank: that sucked.

So I tried to make good on my promise to make sure everyone would be able to see these demos at their own time and pace. This morning I did some recording, I did some editing and I did some publishing. And as of now, all five demos that I planned to do are available on my YouTube channel, and you'll find direct links to them below for convenience. There's also a https://www.youtube.com/playlist?list=PLTJ5vj7osiGO7K70076Y4kjWgoQxfKyJd[playlist] on youtube.com that has all five videos in them. For binge watching ;)

Hope you enjoy and have fun trying out our awesome CDK!


=== Direct links to all videos

* Red Hat Tech Day NL 2017: Installing the CDK on Windows 

video::dpVcg5lop6M[youtube]

* Red Hat Tech Day NL 2017: Installing the CDK on Linux 

video::6JLyKdGY5p4[youtube]


* Red Hat Tech Day NL 2017: Using the CDK to do Java development on Windows 

video::woOoEsk9qcg[youtube]

* Red Hat Tech Day NL 2017: Using the CDK to do dotNET development on Linux 

video::jNgzAoYqC1k[youtube]

* Red Hat Tech Day NL 2017: Using the CDK to quickly test small changes 

video::sQAkzH75YfA[youtube]
